networks:
  shared_network:

services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"
    networks:
      shared_network:

  bot:
    container_name: yt_video_summary_bot
    build: .
    depends_on:
      - mysql
      - telegram-bot-api
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    networks:
      shared_network:

volumes:
  telegram-bot-api-data: